# Generated by Django 4.2.1 on 2023-08-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0004_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('time_log', models.TimeField(help_text='Enter the exact time')),
            ],
        ),
    ]
