# Generated by Django 4.2.1 on 2023-08-16 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0006_alter_menu_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucategory',
            options={'verbose_name': 'Menu Category', 'verbose_name_plural': 'Menu Categories'},
        ),
    ]
