# Generated by Django 4.2.1 on 2023-08-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_app', '0002_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='time',
        ),
        migrations.AddField(
            model_name='reservation',
            name='booking_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
